### ISSUE TITLE
Modded Vphonegaga APK

### ISSUE THREAD

**Issue by AndnixSH** [HuskyDG/systemMagisk#1]
I found modded Vphonegaga that allows to unlock VIP to use Magisk. It's better to use magisk in ramdisk partition than system partition

Android 10 32-bit: [Download VPhone GaGa Gold A10 64Bit apk](https://apkadmin.com/edk567qogxjh/VPhoneGaGa_Gold_V6.1_A10-64Bit_v2.3.6.apk.html)

Android 7 32-bit: [Download VPhone GaGa Gold 32Bit apk](https://apkadmin.com/d209es9lxqv2/VPhoneGaGa_Gold_V6.1_A7-32Bit_v2.3.6.apk.html)

Credit: https://www.youtube.com/c/Goxome

**Comment by HuskyDG** [comment]
I knew this mod but I didn't really like the bad disrespectful behavior of the author (Goxome)

**Comment by AndnixSH** [comment]
Why should the author disrespecting you?

I never contacted him/her but for me, everything seems alright

**Comment by HuskyDG** [comment]
> Why should the author disrespecting you?

Not only me but with others. It's very long time ago, he was banned in many Telegram because of disrespectful behavior, keep promoting hack cheat

**Comment by HuskyDG** [comment]
Since VphoneGaga Mod was here, i decided to archive this repo.

**Comment by AndnixSH** [comment]
I see, I hope he learns the mistakes. at least he seems good on youtube for now
